---
weakauras:
  sync-lua:         sync-lua/main.lua
  root dir:         weakauras
  string file:      string.txt
  table file:       table.txt
  description file: README.md
  verbose sync:     false
  auras:
    -
      name:         Legion Demo Pet Tracker
      source dir:   demo-pet-tracker
      description: >
        Tracks your warlock pets, and `Demonic Empowerment` on them.
      classes:      [Warlock (Demonology)]
      requested by: [Arc]
      versions:
        - id:   "1.1"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Exact Mobcount
      source dir:   exact-mobcount
      description: >
        In Mythic+ dungeons and Challenge Modes, displays exact mobcount
        (e.g. `330/338`) along the usual mobcount percentage.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Loot Method
      source dir:   loot-method
      description: >
        In raids, displays the current loot method (e.g. Master Looter,
        Personal Loot).
      classes:      [All]
      requested by: [Peach]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Loot Spec
      source dir:   loot-spec
      description: >
        Displays your current loot specialization (e.g. `Demonology`). A star
        (e.g. `Demonology*`) means that your loot spec is set to
        `Current Spec`.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Roaring Blaze
      source dir:   roaring-blaze
      description: >
        Displays the current damage multiplier of `Immolate` on your target
        caused by the `Roaring Blaze` talent.
      classes:      [Warlock (Destruction)]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Volcanic Alert
      source dir:   volcanic-alert
      description: >
        Plays an alert sound when you get hit by Volcanic (a Mythic+ affix).
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: "Initial release."
    -
      name:         Gigantic Anger
      source dir:   gigantic-anger
      description: >
        Displays the total amount of Fury generated by the DH legendary ring
        `Anger of the Half-Giants` in the current fight.
      classes:      [DH (Havoc)]
      requested by: [Peach]
      versions:
        - id:   "0.0"
          date: 2016-08-10
          info: "Initial release."
    -
      name:         Exsang Damage
      source dir:   exsang-damage
      description: >
        When you cast `Exsanguinate`, displays the damage being done by your
        hastened bleeds (`Rupture`, `Garrote`).
      classes:      [Rogue (Assassination)]
      requested by: [Zavinn]
      versions:
        - id:   "0.1"
          date: 2016-07-26
          info: "Initial release."
    -
      name:         Pet Follow State
      source dir:   pet-follow-state
      description: >
        Displays whether your pet is in the `Follow` or the `Move To` state.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-07-26
          info: "Initial release."
    -
      name:         Magic Buff
      source dir:   magic-buff
      description: >
        Displays the first Magic buff on the hostile target, if any.
        (For `Spellsteal`, `Purge`, etc.)
      classes:      [All]
      requested by: [Kildon]
      versions:
        - id:   "0.0"
          date: 2016-07-26
          info: "Initial release."
    -
      name:         L.Ring Dmg (Self)
      source dir:   legendary-ring-damage
      description: >
        Shows how much your DPS ring will explode for.
      classes:      [All]
      requested by: [Peach]
      versions:
        - id:   "0.7"
          date: 2016-07-20
          info: "Fixed for Legion pre-patch."
        - id:   "0.6"
          info: >
            Fixed an issue where aura wouldn't deactivate if player died, and
            ring hit no targets.
        - id:   "0.5"
          info: >
            Accuracy fix: previous versions (incorrectly) excluded pet/guardian
            damage; this has been fixed. Fixed some other minor issues. Minor
            display improvement, performance improvement. Name was changed to
            reflect that it works for all DPS rings, not just `Nithramus`.
        - id:   "0.4"
          info: >
            Accuracy fix: damage bonus % is now exact, unrounded number. Fixed
            an issue where aura wouldn't deactivate if player died. (None of
            you experienced this issue, b/c if you die you're bad, and you're
            not bad right?)
        - id:   "0.3"
          info: >
            Accuracy fixes: no longer counts overkill or self-inflicted damage
            (such as `Burning Rush`).
        - id:   "0.2"
          info: >
            Should have fixed the `Prismatic Crystal` double-counting issue.
    -
      name:         Legion Stats Pane
      source dir:   legion-stats-pane
      description: >
        Whenever the stock character stats pane is shown, this WeakAura
        overlays it with a re-creation of the pre-Legion detailed stats pane.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.3"
          date: 2016-07-20
          info: >
            Fixed bug causing a small black square to hang around. Changed
            default positioning to `ANCHOR_OVERLAY`.
        - id:   "0.2"
          info: "Initial release."
    -
      name:         L.Ring CD (Self)
      source dir:   legendary-ring-cd
      description: >
        Shows the CD on your legendary ring, or the remaining buff time if it's
        active. Indicates the status of your own ring only (so it won't trigger
        if someone activates it out of range). Note: It plays a sound on
        activation, which it reads off the `Actions > On Hide` section.
        You can customize it/turn it off there.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-04-09
          info: >
            Fixed wrong time being displayed when 30-sec CD was triggered (e.g.
            from reequipping the ring). Now automatically hides itself if the
            ring is not equipped.
        - id:   "0.0"
          info: "Initial release."
    -
      name:         Zavinn xd
      source dir:   zavinn-xd
      description: >
        Whispers "xd" to Zavinn on BNet every 30 minutes. Change `xdInterval`
        in the `Actions > Init` custom code to alter the interval.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-04-09
          info: >
            Fixed an issue that caused the WeakAura to stop working when the
            computer was restarted.
        - id:   "0.0"
          info: "Initial release."
    -
      name:         Furious Sun Counter
      source dir:   furious-sun-counter
      description: >
        Shows the # of times `Furious Sun` has procced since the start of
        combat (T18 class trinket `Sacred Draenic Incense`, WW proc).
      classes:      [All]
      requested by: [Cherry]
      versions:
        - id:   "0.1"
          date: 2016-03-26
          info: >
            Fixed an issue where the counter could spuriously increment if an
            RSK cast caused combat.
        - id:   "0.0"
          info: "Initial release."
    -
      name:         Savior's Boon
      source dir:   saviors-boon
      description: >
        Shows the ICD for `Savior's Boon` (T18 class trinket
        `Libram of Vindication`, prot pally proc).
      classes:      [Paladin (Prot)]
      requested by: [Brunnor]
      versions:
        - id:   "0.1"
          date: 2016-03-26
          info: "Initial release."
    -
      name:         Temporal Power
      source dir:   temporal-power
      description: >
        Displays the number of stacks and average remaining duration for
        `Temporal Power` (Arcane Mage T18 4pc).
      classes:      [Mage (Arcane)]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-03-04
          info: "Initial release."
    -
      name:         Item Deleter
      source dir:   item-deleter
      description: >
        Periodically sweeps your inventory and deletes specific items. Out of
        the box, it doesn't delete anything. Specify which items to delete by
        going to `Actions > Init` custom code. Then add item names or IDs
        to `itemList`.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-02-16
          info: "Initial release."
    -
      name:         Archi Backstab P3
      source dir:   archi-backstab-p3
      description: >
        Displays the angle of your position with respect to the boss's facing,
        in mythic Archi's P3.
      classes:      [Rogue (Subtlety)]
      requested by: [Zavinn]
      versions:
        - id:   "0.2"
          date: 2016-03-04
          info: >
            It works now, but phase detection is disabled, meaning it will
            display an annoying `--` during Phase 1 and 2.
        - id:   "0.1"
          date: 2016-02-09
          info: "Initial release."