---
readme file:  README.md
readme intro: |-
  # WowCoding
  
  Lua scripts for World of Warcraft.
weakauras:
  sync-lua:         sync-lua/main.lua
  string file:      string.txt
  table file:       table.lua
  description file: README.md
  verbose sync:     false
  auras:
    -
      name:        Prevent Popup Decline
      source dir:  weakauras/prevent-popup-decline
      dev status:  Release
      description: |-
        For certain confirmation popups (accept resurrection, accept summon,
        accept party invite), prevents the Esc key from closing them, and
        makes the `Decline` button smaller.

        ![Screenshot](./screenshot.png?raw=true)
      classes:      [Any]
      requested by: [Arc]
      versions:
        - id:   "1.0"
          date: 2016-09-06
          info: Initial release.
    -
      name:        Absorb Total
      source dir:  weakauras/absorb-total
      dev status:  Release
      description: |-
        Shows total absorbs on you.

        ![Screenshot](./screenshot.png?raw=true)
      classes:      [Any]
      requested by: [Arc]
      versions:
        - id:   "1.0"
          date: 2016-09-02
          info: Initial release.
    -
      name:        Demonwrath Targets
      source dir:  weakauras/demonwrath-targets
      dev status:  Release
      description: |-
        Shows an icon that pulses when `Demonwrath` ticks and displays
        how many targets it hit.

        ![Screenshot](./screenshot.jpg?raw=true)
      classes:      [Warlock (Demonology)]
      requested by: [Arc]
      versions:
        - id:   "1.0"
          date: 2016-08-24
          info: Initial release.
    -
      name:        Demo Pet Tracker
      source dir:  weakauras/demo-pet-tracker
      dev status:  Release
      description: |-
        Tracks your warlock pets, and `Demonic Empowerment` on them.

        ![Screenshot](./screenshot.jpg?raw=true)
      classes:      [Warlock (Demonology)]
      requested by: [Arc]
      versions:
        - id:   "1.2"
          date: 2016-08-23
          info: Initial release.
    -
      name:        Loot Spec
      source dir:  weakauras/loot-spec
      dev status:  Release
      description: |-
        Displays your current loot specialization. A star `*` indicates that
        your loot spec is set to `Current Spec`.

        ![Screenshot](./screenshot.jpg?raw=true)
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: Initial release.
    -
      name:        Roaring Blaze
      source dir:  weakauras/roaring-blaze
      dev status:  Release
      description: |-
        Displays the current damage multiplier of `Immolate` on your target
        caused by the `Roaring Blaze` talent.
      classes:      [Warlock (Destruction)]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-23
          info: Initial release.
    -
      name:        Exact Mobcount
      source dir:  weakauras/exact-mobcount
      dev status:  Release
      description: |-
        In Mythic+ dungeons and Challenge Modes, displays exact mobcount
        along with the usual mobcount percentage.

        ![Screenshot](./screenshot.jpg?raw=true)
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-10
          info: Initial release.
    -
      name:        Loot Method
      source dir:  weakauras/loot-method
      dev status:  Release
      description: |-
        In raids, displays the current loot method (e.g. Master Looter,
        Personal Loot).
      classes:      [All]
      requested by: [Peach]
      versions:
        - id:   "0.0"
          date: 2016-08-10
          info: Initial release.
    -
      name:        Volcanic Alert
      source dir:  weakauras/volcanic-alert
      dev status:  Release
      description: |-
        Plays an alert sound when you get hit by Volcanic (a Mythic+ affix).
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-08-10
          info: Initial release.
    -
      name:        Gigantic Anger
      source dir:  weakauras/gigantic-anger
      dev status:  Release
      description: |-
        Displays the total amount of Fury generated by the DH legendary ring
        `Anger of the Half-Giants` in the current fight.
      classes:      [DH (Havoc)]
      requested by: [Peach]
      versions:
        - id:   "0.0"
          date: 2016-08-10
          info: Initial release.
    -
      name:        Exsang Damage
      source dir:  weakauras/exsang-damage
      dev status:  Release
      description: |-
        When you cast `Exsanguinate`, displays the damage being done by your
        hastened bleeds (`Rupture`, `Garrote`).
      classes:      [Rogue (Assassination)]
      requested by: [Zavinn]
      versions:
        - id:   "0.1"
          date: 2016-07-26
          info: Initial release.
    -
      name:        Pet Follow State
      source dir:  weakauras/pet-follow-state
      dev status:  Release
      description: |-
        Displays whether your pet is in the `Follow` or the `Move To` state.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-07-26
          info: Initial release.
    -
      name:        Magic Buff
      source dir:  weakauras/magic-buff
      dev status:  Release
      description: |-
        Displays the first Magic buff on the hostile target, if any.
        (For `Spellsteal`, `Purge`, etc.)
      classes:      [All]
      requested by: [Kildon]
      versions:
        - id:   "0.0"
          date: 2016-07-26
          info: Initial release.
    -
      name:        Legion Stats Pane
      source dir:  weakauras/legion-stats-pane
      dev status:  Release
      description: |-
        Whenever the stock character stats pane is shown, this WeakAura
        overlays it with a re-creation of the pre-Legion detailed stats pane.

        ![Screenshot](./screenshot.jpg?raw=true)
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.3"
          date: 2016-07-20
          info: |-
            Fixed bug causing a small black square to hang around. Changed
            default positioning to `ANCHOR_OVERLAY`.
        - id:   "0.2"
          date: 2016-05-26
          info: Various features and bugfixes.
        - id:   "0.1"
          date: 2016-05-25
          info: Initial release.
    -
      name:        L.Ring Dmg (Self)
      source dir:  weakauras/legendary-ring-damage
      dev status:  Release
      description: |-
        Shows how much your DPS ring will explode for.
      classes:      [All]
      requested by: [Peach]
      versions:
        - id:   "0.7"
          date: 2016-07-20
          info: "Fixed for Legion pre-patch."
        - id:   "0.6"
          date: 2016-04-09
          info: |-
            Fixed an issue where aura wouldn't deactivate if player died, and
            ring hit no targets.
        - id:   "0.5"
          date: 2016-03-09
          info: |-
            Accuracy fix: previous versions (incorrectly) excluded pet/guardian
            damage; this has been fixed. Fixed some other minor issues. Minor
            display improvement, performance improvement. Name was changed to
            reflect that it works for all DPS rings, not just `Nithramus`.
        - id:   "0.4"
          date: 2015-12-19
          info: |-
            Accuracy fix: damage bonus % is now exact, unrounded number. Fixed
            an issue where aura wouldn't deactivate if player died. (None of
            you experienced this issue, b/c if you die you're bad, and you're
            not bad right?)
        - id:   "0.3"
          date: 2015-12-18
          info: |-
            Accuracy fixes: no longer counts overkill or self-inflicted damage
            (such as `Burning Rush`).
        - id:   "0.2"
          date: 2015-11-09
          info: |-
            Should have fixed the `Prismatic Crystal` double-counting issue.
        - id:   "0.1"
          info: Initial release.
    -
      name:        L.Ring CD (Self)
      source dir:  weakauras/legendary-ring-cd
      dev status:  Release
      description: |-
        Shows the CD on your legendary ring, or the remaining buff time if it's
        active. Indicates the status of your own ring only (so it won't trigger
        if someone activates it out of range). Note: It plays a sound on
        activation, which it reads off the `Actions > On Hide` section.
        You can customize it/turn it off there.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-04-09
          info: |-
            Fixed wrong time being displayed when 30-sec CD was triggered (e.g.
            from reequipping the ring). Now automatically hides itself if the
            ring is not equipped.
        - id:   "0.0"
          date: 2015-12-18
          info: Initial release.
    -
      name:        Zavinn xd
      source dir:  weakauras/zavinn-xd
      dev status:  Release
      description: |-
        Whispers "xd" to Zavinn on BNet every 30 minutes. Change `xdInterval`
        in the `Actions > Init` custom code to alter the interval.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-04-09
          info: |-
            Fixed an issue that caused the WeakAura to stop working when the
            computer was restarted.
        - id:   "0.0"
          date: 2016-03-27
          info: Initial release.
    -
      name:        Furious Sun Counter
      source dir:  weakauras/furious-sun-counter
      dev status:  Release
      description: |-
        Shows the # of times `Furious Sun` has procced since the start of
        combat (T18 class trinket `Sacred Draenic Incense`, WW proc).
      classes:      [All]
      requested by: [Cherry]
      versions:
        - id:   "0.1"
          date: 2016-03-26
          info: |-
            Fixed an issue where the counter could spuriously increment if an
            RSK cast caused combat.
        - id:   "0.0"
          date: 2016-03-25
          info: Initial release.
    -
      name:        Savior's Boon
      source dir:  weakauras/saviors-boon
      dev status:  Release
      description: |-
        Shows the ICD for `Savior's Boon` (T18 class trinket
        `Libram of Vindication`, prot pally proc).
      classes:      [Paladin (Prot)]
      requested by: [Brunnor]
      versions:
        - id:   "0.1"
          date: 2016-03-26
          info: Initial release.
    -
      name:        Temporal Power
      source dir:  weakauras/temporal-power
      dev status:  Release
      description: |-
        Displays the number of stacks and average remaining duration for
        `Temporal Power` (Arcane Mage T18 4pc).
      classes:      [Mage (Arcane)]
      requested by: [Arc]
      versions:
        - id:   "0.1"
          date: 2016-03-04
          info: Initial release.
    -
      name:        Item Deleter
      source dir:  weakauras/item-deleter
      dev status:  Release
      description: |-
        Periodically sweeps your inventory and deletes specific items. Out of
        the box, it doesn't delete anything. Specify which items to delete by
        going to `Actions > Init` custom code. Then add item names or IDs
        to `itemList`.
      classes:      [All]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-02-16
          info: Initial release.
    -
      name:        Archi Backstab P3
      source dir:  weakauras/archi-backstab-p3
      dev status:  Release
      description: |-
        Displays the angle of your position with respect to the boss's facing,
        in mythic Archi's P3.
      classes:      [Rogue (Subtlety)]
      requested by: [Zavinn]
      versions:
        - id:   "0.2"
          date: 2016-03-04
          info: |-
            It works now, but phase detection is disabled, meaning it will
            display an annoying `--` during Phase 1 and 2.
        - id:   "0.1"
          date: 2016-02-09
          info: Initial release.
    -
      name:        Mana Potency
      source dir:  archived/mana-potency
      dev status:  Archived
      description: |-
        Shows your current damage multiplier for the (pre-Legion)
        Arcane Mage mastery.
      classes:      [Mage (Arcane)]
      requested by: [Arc]
      versions:
        - id:   "0.0"
          date: 2016-03-04
          info: Initial release.
    -
      name:        Target Threat Situation
      source dir:  archived/target-threat-situation
      dev status:  Archived
      description: |-
        Shows a subset of your target's threat table in a text display
        (including the primary target, the top threat tank, the top threat
        non-tank, and yourself). Plays an audio alert if you're in a tank spec
        and a non-tank has aggro or top threat. You can adjust options under
        `Actions > On Init` custom code.
      classes:      [All]
      requested by: [Kildon]
      versions:
        - id:   "0.0"
          date: 2016-01-12
          info: Initial release.
    -
      name:        Arcane Blast Bar
      source dir:  archived/arcane-blast-bar
      dev status:  Archived
      description: |-
        Shows timer bars for Arcane Blast (cast) and Arcane Charge debuff.
      classes:      [Mage (Arcane)]
      requested by: [Kildon]
      versions:
        - id:   "0.0"
          date: 2016-01-02
          info: Initial release.
    -
      name:        Raid Interrupts
      source dir:  archived/raid-interrupts
      dev status:  Archived
      description: |-
        Shows a raid frame-like grid with available interrupts and cooldowns,
        and shows a message when someone interrupts. NOT updated for Legion
        class changes; I may revive this if there is enough interest.
      classes:      [All]
      requested by: [Kildon, Chambers]
      versions:
        - id:   "0.0"
          date: 2015-11-18
          info: Initial release.
